# Changes here will be overwritten by Copier.
_commit: 1.8.4
_src_path: gh:pawamoy/copier-uv
author_email: vandy.goel23@gmail.com
author_fullname: Vandit Goel
author_username: vandyG
copyright_date: '2025'
copyright_holder: Vandit Goel
copyright_holder_email: vandy.goel23@gmail.com
copyright_license: MIT
insiders: false
project_description: CNN model for imagenette data.
project_name: imagenette-cnn
python_package_command_line_name: imagenette-cnn
python_package_distribution_name: imagenette-cnn
python_package_import_name: imagenette_cnn
repository_name: imagenette-cnn
repository_namespace: vandyG
repository_provider: github.com

